name: on-pr
on: [push, pull_request]
jobs:
  build: # might not need to check sudo
    strategy:
      matrix:
        os: ['ubuntu-18.04']
        perl: ['5.26'] # TODO this version of perl threading support# multithreading (5.26-shrplib - in travis) add threading support
        
    runs-on: ${{matrix.os}} 
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}  # can simplify this if no other versions/os' are needed
    steps:
    - uses: actions/checkout@v2 # versioning (check )
    
    #install libgd-dev
    - name: install libgd-de and uuid-dev #TODO add cpanminus (potentially)
      run:
          sudo apt-get install -y libgd-dev uuid-dev # TODO change to cache method? -  5GB limit on caches
        

    #run the travis install
    - name: travis script
      run: |
          echo "/home/travis/miniconda/samtools/bin" >> $GITHUB_PATH
          ${GITHUB_WORKSPACE}/scripts/travis_install.sh $WTSI_NPG_GITHUB_URL $WTSI_NPG_CONDA_REPO $WTSI_NPG_BUILD_BRANCH # TODO add path if errors on location of files
      env:
        WTSI_NPG_GITHUB_URL: https://github.com/wtsi-npg
        WTSI_NPG_CONDA_REPO: https://dnap.cog.sanger.ac.uk/npg/conda/prod/generic
        WTSI_NPG_BUILD_BRANCH: ${GITHUB_HEAD_REF} #getting name of current github branch
      
    - name: Checking perl5lib
      run: |
          perl -V:'install.*'
          echo "This is perl5lib: $PERL5LIB"
          echo ""
          echo "this is current location:"
          pwd

    - name: install cpanm and multiple modules
      #uses: perl-actions/install-with-cpanm@v1 
      run: |
          #cpanm --sudo --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
          eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
          cpanm --installdeps .

    - name: run Build.PL and ./Build   
      run: |
          eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
          export TEST_AUTHOR=1
          perl Build.PL && ./Build test --verbose # might have to add path

    - name: Archive CPAN logs
      if: ${{ failure() }}
      uses: actions/upload-artifact@v2
      with:
        name: cpan_log
        path: /home/runner/.cpanm/work/*/build.log
        retention-days: 5
